### ISSUE TITLE
Fix todos display

### ISSUE THREAD

**Issue by JoleneKearse** [princemuel/fm-todoist#62]
Each todo in the list has 'text' after it.

![image](https://user-images.githubusercontent.com/70668540/199614925-2a3b4998-c855-4122-8498-926ea3d2d815.png)

**Comment by princemuel** [comment]
Wow, I thought, I'd removed that 🤣

**Comment by princemuel** [comment]
Wow, I thought, I'd removed that 🤣

**Comment by JoleneKearse** [comment]
I just noticed it! LOL

**Comment by princemuel** [comment]
Okay let me work on it

**Comment by JoleneKearse** [comment]
👍

**Comment by princemuel** [comment]
This issue is closed by [PR#64](https://github.com/princemuel/fm-todoist/pull/64)
